### ISSUE TITLE
Multiple transcript in a single html page not workig properly

### ISSUE THREAD

**Issue by webdesignershahid** [samuelbradshaw/transcript-tracer-js#1]
I have multiple transcript in a single html file.
![Screenshot_1](https://github.com/samuelbradshaw/transcript-tracer-js/assets/121008410/e44857ae-de4f-416d-878b-8b98271e8ce3)

There is several button/audio also available for the tt-transcript.
![Screenshot_2](https://github.com/samuelbradshaw/transcript-tracer-js/assets/121008410/c2cfec65-8929-47a9-81c7-28b9b8c1553f)

whenever I playing the audio of the block, its sound playing but text are not highliting accordingly data-tt-transcript="0" or data-tt-transcript="1" or data-tt-transcript="3". Maybe there is a issue with blocks.

Please can you check this with a simple demo. just need multiple transcript with several audio and .vtt.

Thanks for your time.

**Comment by samuelbradshaw** [comment]
Thanks for reporting this, and sorry for the delay in responding! I pushed some changes to the JavaScript that I think will fix the issue (https://github.com/samuelbradshaw/transcript-tracer-js/commit/35538c4d8a7b585036455705390dc36bcd3db299). I also added an example with multiple audio files on the same page. Let me know if it works!

**Comment by webdesignershahid** [comment]
Hi Samuel Bradshaw,

Thanks for your quick response and a great thanks for the solutions. Its
working nicely.

Thanks again

Regards
Shahidul
